### ISSUE TITLE
Fix missing libraries when building with Fuseki 2.3.1

### ISSUE THREAD

**Issue by flamingofugang** [rdfhdt/hdt-java#10]
Hi,

I got the following error message when I build the current version with Fuseki 2.3.1

    [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.1:compile (default-compile) on project hdt-fuseki: Compilation failure: Compilation failure:
    [ERROR] /home/fug2/hdt-java/hdt-fuseki/src/main/java/org/rdfhdt/hdt/fuseki/FusekiHDTCmd.java:[21,36] error: package org.apache.jena.fuseki does not exist
    [ERROR] 
    [ERROR] /home/fug2/hdt-java/hdt-fuseki/src/main/java/org/rdfhdt/hdt/fuseki/FusekiHDTCmd.java:[21,0] error: static import only from classes and interfaces
    [ERROR] 
    [ERROR] /home/fug2/hdt-java/hdt-fuseki/src/main/java/org/rdfhdt/hdt/fuseki/FusekiHDTCmd.java:[31,29] error: package org.apache.jena.fuseki does not exist
    [ERROR] 
    [ERROR] /home/fug2/hdt-java/hdt-fuseki/src/main/java/org/rdfhdt/hdt/fuseki/FusekiHDTCmd.java:[32,33] error: package org.apache.jena.fuseki.mgt does not exist
    [ERROR] 
    [ERROR] /home/fug2/hdt-java/hdt-fuseki/src/main/java/org/rdfhdt/hdt/fuseki/FusekiHDTCmd.java:[33,36] error: package org.apache.jena.fuseki.server does not exist
    [ERROR] 
    [ERROR] /home/fug2/hdt-java/hdt-fuseki/src/main/java/org/rdfhdt/hdt/fuseki/FusekiHDTCmd.java:[34,36] error: package org.apache.jena.fuseki.server does not exist
    [ERROR] 
    [ERROR] /home/fug2/hdt-java/hdt-fuseki/src/main/java/org/rdfhdt/hdt/fuseki/FusekiHDTCmd.java:[35,36] error: package org.apache.jena.fuseki.server does not exist
    [ERROR] 
    [ERROR] /home/fug2/hdt-java/hdt-fuseki/src/main/java/org/rdfhdt/hdt/fuseki/FusekiHDTCmd.java:[40,31] error: package org.eclipse.jetty.server does not exist
    [ERROR] 
    [ERROR] /home/fug2/hdt-java/hdt-fuseki/src/main/java/org/rdfhdt/hdt/fuseki/FusekiHDTCmd.java:[46,14] error: package arq.cmd does not exist
    [ERROR] 
    [ERROR] /home/fug2/hdt-java/hdt-fuseki/src/main/java/org/rdfhdt/hdt/fuseki/FusekiHDTCmd.java:[47,18] error: cannot find symbol
    [ERROR] 
    [ERROR] package arq.cmdline
    [ERROR] /home/fug2/hdt-java/hdt-fuseki/src/main/java/org/rdfhdt/hdt/fuseki/FusekiHDTCmd.java:[51,28] error: package com.hp.hpl.jena.graph does not exist
    [ERROR] 
    [ERROR] /home/fug2/hdt-java/hdt-fuseki/src/main/java/org/rdfhdt/hdt/fuseki/FusekiHDTCmd.java:[52,28] error: package com.hp.hpl.jena.query does not exist
    [ERROR] 
    [ERROR] /home/fug2/hdt-java/hdt-fuseki/src/main/java/org/rdfhdt/hdt/fuseki/FusekiHDTCmd.java:[53,28] error: package com.hp.hpl.jena.query does not exist
    [ERROR] 
    [ERROR] /home/fug2/hdt-java/hdt-fuseki/src/main/java/org/rdfhdt/hdt/fuseki/FusekiHDTCmd.java:[54,34] error: package com.hp.hpl.jena.sparql.core does not exist
    [ERROR] 
    [ERROR] /home/fug2/hdt-java/hdt-fuseki/src/main/java/org/rdfhdt/hdt/fuseki/FusekiHDTCmd.java:[55,34] error: package com.hp.hpl.jena.sparql.core does not exist
    [ERROR] 
    [ERROR] /home/fug2/hdt-java/hdt-fuseki/src/main/java/org/rdfhdt/hdt/fuseki/FusekiHDTCmd.java:[56,34] error: package com.hp.hpl.jena.sparql.core does not exist
    [ERROR] 
    [ERROR] /home/fug2/hdt-java/hdt-fuseki/src/main/java/org/rdfhdt/hdt/fuseki/FusekiHDTCmd.java:[57,26] error: package com.hp.hpl.jena.tdb does not exist
    [ERROR] 
    [ERROR] /home/fug2/hdt-java/hdt-fuseki/src/main/java/org/rdfhdt/hdt/fuseki/FusekiHDTCmd.java:[58,26] error: package com.hp.hpl.jena.tdb does not exist
    [ERROR] 
    [ERROR] /home/fug2/hdt-java/hdt-fuseki/src/main/java/org/rdfhdt/hdt/fuseki/FusekiHDTCmd.java:[59,38] error: package com.hp.hpl.jena.tdb.transaction does not exist
    [ERROR]

**Comment by bendiken** [comment]
It sounds as though @hinahiroy is having the same issue as well.

**Comment by bendiken** [comment]
This should be resolved by #11, please report back.

**Comment by bendiken** [comment]
Closing as this should be resolved now. Please reopen in case not.

**Comment by pcechz** [comment]
i am haviing dis kinda prob too

**Comment by flamingofugang** [comment]
This should be fixed now, try 'git pull' then 'mvn package'
