### ISSUE TITLE
Explicit System.gc() call uses 20% of my CPU time

### ISSUE THREAD

**Issue by Aklakan** [rdfhdt/hdt-java#102]
While processing a large number of HDT files in Java, I noticed in the VisualVM profiler that 20% of my CPU time is spent on HDT.close(). Please remove any explicit System.gc() call in the code.
In my case, it is this particular instance:

https://github.com/rdfhdt/hdt-java/blob/4e274ef4207ae66c6c8fc867587a4cb12709ed89/hdt-java-core/src/main/java/org/rdfhdt/hdt/compact/sequence/SequenceLog64Map.java#L277

**Comment by mielvds** [comment]
I didn't write this code, so i'm assuming it's there to prevent heap memory overflows.
It is actually possible to disable explicit System.gc() via the java argument -XX:+DisableExplicitGC.

**Comment by Aklakan** [comment]
Hi, the jvm option workaround works but it is quite clunky though. As in this case System.gc is called on close, devs should just manually invoke it after hdt.close if they really want/need it. For me, the GC overhead was a big performance issue when processing a small sample of 10000 hdt files - not the memory. It is likely other devs will face the same issue as hdt is becoming increasingly popular.

**Comment by mielvds** [comment]
Fair enough. Done in https://github.com/rdfhdt/hdt-java/commit/5b4c5b06a51135f9ef6fa5a61a42589ef7a395ce and warning added to README.
