### ISSUE TITLE
org.codehaus.mojo:exec-maven-plugin:1.6.0:java

### ISSUE THREAD

**Issue by JohanneBakalara** [rdfhdt/hdt-java#105]
Hi !
I tried to use the conversion HDT2RDF and RDF2HDT but I have the following error. 
I tried on java-1.8 and java-11, and on two OS : Unbuntu 18 and fedora 31 but I always have the same problem. I succeed to build it with eclipse so it looks like the problem comes from Maven. (I did the mvn install and the mvn assembling:single as explained in the doc).
Could you point it out what I did wrong ?

Thanks for help !
 
`[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------< org.apache.maven:standalone-pom >-------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.232 s
[INFO] Finished at: 2020-03-01T19:05:23+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli): Goal requires a project to execute but there is no POM in this directory (/home/jbakalar/hdt-java-master/hdt-java-cli/bin). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException
`

**Comment by mielvds** [comment]
@JohanneBakalara does this issue still occur with the latest version?
