### ISSUE TITLE
Problem with SortUtils

### ISSUE THREAD

**Issue by D063520** [rdfhdt/hdt-java#108]
Hi,

I'm running hdtCat on a large file. Everything goes fine until an error is throw in:

https://github.com/rdfhdt/hdt-java/blob/678601e91f62329299a177f68f2d3af18c7b1b20/hdt-java-core/src/main/java/org/rdfhdt/hdt/util/SortUtils.java#L75

java.lang.ArrayIndexOutOfBoundsException

As far as I see the problem is not in HDTCat. In fact if I run the code on the same files on a version of hdt-java before the new SortUtils was introduced this is not happening.

In HDTCat this is happening when searching over an hdt file. So this is an issue affecting not only hdtCat but whole HDT. 

I'm not sure how to exactly debug this currently. I will try to add some more debug information ...

Salut

**Comment by mielvds** [comment]
@D063520 is the thrown error the same as in https://github.com/rdfhdt/hdt-java/issues/93 ? I saw @AlyHdr made a copy of `SortUtils.java`. Does that version mitigate the problem somehow?

**Comment by AlyHdr** [comment]
Yes basically `SortUtils.java` is not used anymore in the code base.
