### ISSUE TITLE
rdf2hdt does not terminate

### ISSUE THREAD

**Issue by PhilippChr** [rdfhdt/hdt-java#111]
Hello,

I tried running the rdf2hdt converter in three different ways
bash bin/rdf2hdt.sh -options Xmx200G <input> <output>
bash bin/rdf2hdt.sh -options -Xmx200G <input> <output>
bash bin/rdf2hdt.sh -options '-Xmx200G' <input> <output>

but it does not make any progress at some point, and does not terminate even a week after starting it with nohup.
The CPU load is about 1000 (in %). The size of the input dump is about 40 GB.

Do you have any suggestion how to overcome these problems?]
Thanks!

**Comment by mielvds** [comment]
Hi @PhilippChr ! How many triples?

**Comment by D063520** [comment]
@PhilippChr can you try with the latest version ... it might have changed ...
also as @mielvds pointed out, can you describe the datasets ....

**Comment by PhilippChr** [comment]
Hi @mielvds and @D063520,
Thanks a lot for your comments! The input had roughly 2 billion triples.
We managed to overcome the problem, but I can‘t remember the details really.
I think we tried out several configurations and it eventually worked.
I would close the issue therefore.
Regards,
Philipp
