### ISSUE TITLE
2 versions of UnicodeEscape. Subtly different

### ISSUE THREAD

**Issue by JervenBolleman** [rdfhdt/hdt-java#116]
This code seems duplicated between [hdt-java-core/src/main/java/org/rdfhdt/hdt/util/string/UnicodeEscape.java] and [hdt-api/src/main/java/org/rdfhdt/hdt/util/UnicodeEscape.java]. Could we delete one of the two files?

**Comment by mielvds** [comment]
Nice catch. The one in core wasn't used, so deleted in https://github.com/rdfhdt/hdt-java/commit/d54e78be9d8d9e2eee2e4395e34ffa904fbedb65
