### ISSUE TITLE
calculate memory requirements for hdt generation

### ISSUE THREAD

**Issue by jjkoehorst** [rdfhdt/hdt-java#124]
I am currently converting a wide variety of datasets to the HDT format while most of them are relatively small and can be converted using the default java memory requirements some will run out of heap space. Since I am running many of them in parallel I would like to optimise the memory requirements for the conversion.

Now my question is if there is a way to calculate how much memory HDT conversion roughly needs for 1, 10, 100, 1000 million triples and is this consistent?

**Comment by mielvds** [comment]
Hard to say. The determining factor is actually the dictionary and that scales with the number of unique URIs and literals.

**Comment by mielvds** [comment]
This might be the best estimate we can give. Everything exact requires a list of pre-computed statistics and even then it depends on what dictionary you use, etc.
