### ISSUE TITLE
Make sure bytebuffer never exceeds Integer.MAX_VALUE

### ISSUE THREAD

**Issue by mielvds** [rdfhdt/hdt-java#126]
A limitation of FileChannel ( = class to memory map files) causes issues with large files, because it doesn't allow sizes beyond Integer.MAX_VALUE by design due to compatibility with JVM implementations. See https://stackoverflow.com/questions/8076472/why-does-filechannel-map-take-up-to-integer-max-value-of-data

HDT defines a number of blocks per bytebuffer, which is currently fixed to 50000. It maps one bytebuffer at a time into memory. A solution is probably to calculate the amount of blocks so the bytebuffer never exceeds Integer.MAX_VALUE.

**Comment by D063520** [comment]
ok i see .... maybe the best is to debug this with a dataset at hand ... if someone can provide would be great!

**Comment by mielvds** [comment]
Internet archive has a copy: https://web.archive.org/web/20191007051902/http://gaia.infor.uva.es/hdt/dbpedia2016-10/dbpedia2016-10.hdt
