### ISSUE TITLE
Problem in hdtCat when compressing on small machine or many literals

### ISSUE THREAD

**Issue by D063520** [rdfhdt/hdt-java#130]
Currently in hdtCat the two file are merged until a certain threshold is reached:

https://github.com/rdfhdt/hdt-java/blob/2f22964abb2309b33a752fa18b62d530f932abe8/hdt-java-core/src/main/java/org/rdfhdt/hdt/dictionary/impl/FourSectionDictionaryCat.java#L334

This can cause memory problems if the memory for the JVM is to small or if there are many literals that are very long.

**Comment by mielvds** [comment]
Fixed by #131
