### ISSUE TITLE
Increment HDT and index version to 3.0.0

### ISSUE THREAD

**Issue by mielvds** [rdfhdt/hdt-java#146]
Because of the breaking changes in 3.0.0, the info in https://github.com/rdfhdt/hdt-java/blob/master/hdt-api/src/main/java/org/rdfhdt/hdt/hdt/HDTVersion.java class need to be updated accordingly. (This generates the current v1-1 suffix on the index file)

**Comment by D063520** [comment]
Hi, which are the breaking changes? As far as I know there are none ....

**Comment by mielvds** [comment]
I think this one: https://github.com/rdfhdt/hdt-java/pull/139 
Anyway, for future reference:
- if the HDT changes, update https://github.com/rdfhdt/hdt-java/blob/master/hdt-api/src/main/java/org/rdfhdt/hdt/hdt/HDTVersion.java#L8
- if the .index file changes, update https://github.com/rdfhdt/hdt-java/blob/master/hdt-api/src/main/java/org/rdfhdt/hdt/hdt/HDTVersion.java#L12

**Comment by D063520** [comment]
Hi,

you are right. I thought this was not committed yet.

But everything should be fine. When the HDT with the new dictionary is generated it has a different version:

[hdt-api/src/main/java/org/rdfhdt/hdt/hdt/HDTVersion.java](https://github.com/AlyHdr/hdt-java/blob/fb33ab9bfe944f614db96d9926dccc991bcb592c/hdt-api/src/main/java/org/rdfhdt/hdt/hdt/HDTVersion.java)

So basically everything remains compatible. The index is the same as before so this should not change.

Or do I miss something?

**Comment by mielvds** [comment]
Yeah I don't really understand the meaning of this `_2`... If the HDT changes, the version simply changes. Why this addition?

**Comment by D063520** [comment]
So basically in the 3.0.0 branch there are now two types of HDT supported ... the orignal one and the one where the dictionary is split by datatype. Depending which we generate we mark with HDT 1 or 2. If you try to open an HDT_2 with the c++ version an error will be throw that the version is not compatible. With the java version he will just interpret it correctly. Makes sense?

**Comment by mielvds** [comment]
Yep! That makes sense. There are probably better ways to maintain this versioning system, we might have to refactor this at some point.
