### ISSUE TITLE
Setup Github Action for Maven release

### ISSUE THREAD

**Issue by mielvds** [rdfhdt/hdt-java#151]
https://github.com/marketplace/actions/maven-release-and-publish

**Comment by D063520** [comment]
Hi,

we are done for now with the changes we needed:

- hdtCat
- hdtDiff
- new dictionary
we would need a dependency now for the new branch ... maybe a pre-release? How can we proceed on that?

**Comment by D063520** [comment]
@mielvds do you have the credentials? We can try to take care of this ....

**Comment by mielvds** [comment]
I have, but they are personal. I'll see if i can create some for you or have some neutral ones.

FYI, this that need to be done for every manual MVM release

Set the `~/.m2/settings.xml`
``` xml
<settings>
  ...
  <servers>
    ...
    <server>
      <id>sonatype-nexus-snapshots</id>
      <username>your-sonatype-id</username>
      <password>your-sonatype-pwd</password>
    </server>
    <server>
      <id>sonatype-nexus-staging</id>
      <username>your-sonatype-id</username>
      <password>your-sonatyp-pwd</password>
    </server>
    <server>
      <id>github</id>
      <username>your-github-id</username>
      <password>your-github-pwd</password>
    </server>
  </servers>
  ...
</settings>
```


export RC_VERSION=2.1.2

**Comment by D063520** [comment]
Maybe one option is to add your credentials in thegithub action secrets
https://github.com/rdfhdt/hdt-java/settings/secrets/actions
I'm not sure but no one else might be able to see them, but we can still use them ....

**Comment by mielvds** [comment]
sounds good! credentials are added

**Comment by D063520** [comment]
Mhmm ... was not that successfull ..... I created a new workflow for this:

https://github.com/rdfhdt/hdt-java/blob/master/.github/workflows/main.yml

This will be triggered on release and it is fine but it fails

https://github.com/rdfhdt/hdt-java/runs/5392029498?check_suite_focus=true

with a  401 Unauthorized

**Comment by mielvds** [comment]
I'll see if I can figure out what the issue is

**Comment by D063520** [comment]
I have a theory .... this ID might be wrong
https://github.com/rdfhdt/hdt-java/blob/f6b64aaeeca5ef6dd1499b98937d972ec10539e8/.github/workflows/main.yml#L18
if what you pasted above is right ....

**Comment by mielvds** [comment]
yep, that's definitely an issue!

**Comment by mielvds** [comment]
@D063520 I believe Nexus staging rejects everything not `-SNAPSHOT... but in any case: there are very cumbersome rules to deploy maven packages and I think you better check how this is handled first. Last time, @awoods helped me out, but it didn't stick with me.

**Comment by D063520** [comment]
It worked in fact .... we need just to check it appears on mvn central .....

**Comment by D063520** [comment]
@mielvds I think something went wrong .... which is strange since the CI did not complain
could you try to do it locally and note down the steps? It would be easier to configure the CI than properly ....

Other thing, could it be that you need to do a manual step by logging in:

`To release your components, you can either release them directly from the command line, if you are using the Nexus Staging Maven Plugin or Ant Tasks or open your favorite browser and go to https://s01.oss.sonatype.org/ or follow our [detailed instructions](https://central.sonatype.org/publish/release/).`
from https://central.sonatype.org/publish/release/#locate-and-examine-your-staging-repository

**Comment by D063520** [comment]
@mielvds I checked again the documentation. If I'm not wrong all went fine, but there is currently still a manual action required described here:

https://central.sonatype.org/publish/release/

can you check?

**Comment by D063520** [comment]
Ok, I advanced a bit ... so I added and configured a plugin that automatically passes from the staging step to the release step. So this is fine. Also I'm signing now the artifcat. I think all should be fine this time. Let's see if it appears in mvn central tomorrow morning ...

**Comment by D063520** [comment]
yes i think it is ..
<img width="1680" alt="Screenshot 2022-03-10 at 22 58 01" src="https://user-images.githubusercontent.com/10883585/157761653-07269453-d5b6-43e9-9eea-44819e43a575.png">

**Comment by D063520** [comment]
It is now in maven central:

**Comment by mielvds** [comment]
Hi @D063520 , awesome, you made it work! The delay is normal. IIRC the sonatype repo is not maven central, but syncs everything to maven central with a delay.

**Comment by mielvds** [comment]
@D063520 Seems to have worked: https://mvnrepository.com/artifact/org.rdfhdt/hdt-java-core
