### ISSUE TITLE
Please update to a recent 2.x Jena version

### ISSUE THREAD

**Issue by egonw** [rdfhdt/hdt-java#2]
For example, 2.12.1... I gave it a go, but running into Jena API changes around the ReorderTransformationBase class :/ However, I am not familiar with these APIs so cannot update this myself...

**Comment by mielvds** [comment]
I think it would be Jena 3 directly though. I can have take a look, but idea when.

**Comment by MarioAriasGa** [comment]
Hi egon, I was playing with this over the weekend. I fixed the ReorderTransformation class but I haven't updated our fuseki-hdt fork to have a SPARQL endpoint. Do you want to use it programmatically? I can push the branch if you want to play with it.

**Comment by bendiken** [comment]
@MarioAriasGa Please do push the branch. We are trying to get people set up with HDT tooling and get them going with HDT conversions here at the [SWAT4LS hackathon](http://www.swat4ls.org/workshops/cambridge2015/programme/hackathon/), and are running into some pain points such as this one.

I believe @egonw is working on demonstrating the execution of a SPARQL query on top of an HDT file, and anything which could help with that (e.g., examples) would be very welcome.

**Comment by MarioAriasGa** [comment]
I have uploaded the branch hdt-jena-3.0.0, feel free to try it.

Under the hdt-jena project, there is an hdtsparql.sh commandline (it is also available when generating the whole package)

Sorry I didn't arrive in time for the hackathon.

Mario.

**Comment by mielvds** [comment]
Great! now we can update the LDF-Java server to Jena 3 as well

**Comment by RubenVerborgh** [comment]
Thanks, @MarioAriasGa!

**Comment by bendiken** [comment]
Closing this issue as the Jena 3.x branch has been merged.
