### ISSUE TITLE
FILTER does not work :(

### ISSUE THREAD

**Issue by bdecarne** [rdfhdt/hdt-java#25]
Hello there, 

I am using hdt-jena to query over the geonames HDT. I am unabled to use a FILTER. 

Look at this : 
```sparql
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#> 
SELECT ?s ?lat ?long 
WHERE {
   ?s geo:lat ?lat. 
   ?s geo:long ?long
} LIMIT 10
```

I successfully get : 
```
s,lat,long
_:b0,35.325,-71.085641
_:b0,35.325,-80.00
_:b0,35.325,13.286104
_:b0,35.325,2.15898513793945
_:b0,35.325,2.312922
_:b0,35.325,25.13
_:b0,35.325,9.221907
_:b0,40.44,-71.085641
_:b0,40.44,-80.00
_:b0,40.44,13.286104
```
Now a try to filter over geo:lat : 

```sparql
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#> 
SELECT ?s ?lat ?long 
WHERE {
   ?s geo:lat ?lat. 
   ?s geo:long ?long. 
   FILTER(?lat > 40)
} LIMIT 10
```
Unfortunately, no more result : 

```
s,lat,long
```

So, can you tell me if FILTER is out of HDT capabilities ? 

I crawled the code, and I found this line : 

```
//      // FIXME: Allow a filter here.     
```
https://github.com/rdfhdt/hdt-java/blob/master/hdt-jena/src/main/java/org/rdfhdt/hdtjena/solver/StageMatchTripleID.java#L143

Regards,

**Comment by bendiken** [comment]
@egonw, you have any familiarity with `FILTER` in this implementation?

**Comment by egonw** [comment]
No. As the code link suggests, it does not seem to be implemented right now... and while I understand what needs to be done, I have no clue how to do this efficiently...

**Comment by bdecarne** [comment]
As i understand, FILTER is done by Jena ARQ. But : in the geonames HDT, geo:lat and geo:long are defined as string, not float. 

Jena ARQ is unable to compare float vs string, but the error is not thrown. I had to cast my variable : 

```
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT ?s ?lat ?long 
WHERE {
   ?s geo:lat ?lat. 
   ?s geo:long ?long. 
   FILTER(xsd:float(?lat) > 40)
} LIMIT 10
```
It works fine.
