### ISSUE TITLE
HDT-CPP is not able to load HDT file created in HDT-Java

### ISSUE THREAD

**Issue by webdata** [rdfhdt/hdt-java#30]
Apparently there is a bug in the format synchronization between HDT-JAVA  and HDT-CPP. One HDT file created in HDT-Java cannot be loaded in HDT-CPP (the inverse is working fine).

**Comment by mielvds** [comment]
could have something todo with the array extensions that were added recently https://github.com/rdfhdt/hdt-java/commit/0fec61bfe40cf364ebb19e4661c4133e5de89cb6

**Comment by webdata** [comment]
Thanks @mielvds. In fact it was a problem in the dictionary of HDT-cpp, which was expecting metadata (sizeStrings) that is not really needed. 

Fixed in https://github.com/rdfhdt/hdt-cpp/commit/e44f6b3487042022aa33e883685f65c3d809d760

**Comment by bendiken** [comment]
Related issue: https://github.com/rdfhdt/hdt-cpp/issues/7
