### ISSUE TITLE
Publish 2.0 as maven artifact

### ISSUE THREAD

**Issue by mielvds** [rdfhdt/hdt-java#32]
The 2.0 version of this codebase is not available yet on Maven Central, but I don't have to permissions to do so. @MarioAriasGa or @webdata can you do that or give me the right access?

**Comment by mielvds** [comment]
@MarioAriasGa I'm getting a lot of questions from the LDF server on this, could you please publish or give me access to the repo?

**Comment by namedgraph** [comment]
I second the need for Maven dependency

**Comment by mielvds** [comment]
Closed in favor of #78
