### ISSUE TITLE
Generated HDT file incompatible

### ISSUE THREAD

**Issue by RubenVerborgh** [rdfhdt/hdt-java#35]
The HDT file generated by hdt-java from http://experimental.worldcat.org/fast/download/FASTTitle.nt.zip is incompatible with hdt-cpp. When generating the file with hdt-cpp, it is compatible with both versions.

**Comment by MarioAriasGa** [comment]
I have tested this with the latest java/master and it loads correctly with the latest cpp/devel
Have you ever found another file with this issue? Or shall we close the ticket?
