### ISSUE TITLE
hdtSearch.sh and Fuseki give incorrect results for non-ASCII literals

### ISSUE THREAD

**Issue by osma** [rdfhdt/hdt-java#36]
I noticed problems with both hdtSearch (cpp) and hdtSearch.sh (java). Both apparently give incorrect results in some cases when looking for a specific literal value. I have reported the problems with the cpp version in [a separate issue](https://github.com/rdfhdt/hdt-cpp/issues/55).

My test dataset is this NT file with only 3 triples:
```
<http://example.org/000046085> <http://schema.org/name> "Raamattu" .
<http://example.org/000146854> <http://schema.org/name> "Ajan lyhyt historia" .
<http://example.org/000019643> <http://schema.org/name> "Seitsemän veljestä" .
```

I converted it to HDT using the Java version of rdf2hdt. Then I query it for the literal values using hdtSearch.sh:

```
$ rdf2hdt.sh hdt-test.nt hdt-test.hdt
Converting hdt-test.nt to hdt-test.hdt as null
File converted in: 47 ms 744 us 0.0                            
Total Triples: 3
Different subjects: 3
Different predicates: 1
Different objects: 3
Common Subject/Object:0
HDT saved to file in: 3 ms 441 us

$ hdtSearch.sh hdt-test.hdt
Could not read .hdt.index, Generating a new one.
Predicate Bitmap in 319 us
Count predicates in 26 us
Count Objects in 41 us Max was: 1
Bitmap in 23 us
Object references in 39 us
Sort object sublists in 8 us
Count predicates in 17 us
Index generated in 314 us
>> ? ? "Raamattu"
Query: |?| |?| |"Raamattu"|
http://example.org/000046085 http://schema.org/name "Raamattu"
Iterated 1 triples in 7 ms 384 us
>> ? ? "Ajan lyhyt historia"
Query: |?| |?| |"Ajan lyhyt historia"|
http://example.org/000146854 http://schema.org/name "Ajan lyhyt historia"
Iterated 1 triples in 261 us
>> ? ? "Seitsemän veljestä"
Query: |?| |?| |"Seitsemän veljestä"|
No results found.
```

As you can see from the above output, the first and second queries (for "Raamattu" and "Ajan lyhyt historia") give the correct result, but the last one gives zero results even though it should match one triple in the data.

Likewise, if I start up Fuseki using `hdtEndpoint.sh` and perform this SPARQL query:
```
SELECT * { ?s ?p "Seitsemän veljestä" }
```
I get no results, but similar queries for the two other literal values do give the correct result. I tried this query both directly via the Fuseki UI and via YASGUI.org, just in case there would be some problem with character encodings. The query appears as it should in the Fuseki log/console, there are no obvious encoding problems.

I'm not sure whether the problem is in the HDT generation, index file generation, or querying.

**Comment by osma** [comment]
I also tried generating the HDT file using `rdf2hdt` from hdt-cpp, and generating the index with `hdtSearch` also from hdt-cpp. I still get the same incorrect results with `hdtSearch.sh`.

**Comment by osma** [comment]
This appears to be an encoding problem on some level. I removed all the spaces in the literals, which had no effect on the results (in contrast to the hdt-cpp issue, where space handling seem to be at least part of the problem). However, as soon as I added a non-ASCII character to one of the literals, it stopped matching the query.

**Comment by webdata** [comment]
I will fix the space problem as in https://github.com/rdfhdt/hdt-cpp/issues/55, and have a look at the encoding

**Comment by osma** [comment]
There is no space problem here AFAICT, only an encoding problem.

**Comment by osma** [comment]
I tried debugging this by placing breakpoints and stepping through them in Eclipse while running hdtSearch. I got as far as finding out that `PFCDictionarySectionMap.locateInBlock` behaves as if the serched string ("Seitsemän veljestä") wasn't present in the dictionary at all - it behaved in exactly the same way if I tried another string that genuinely wasn't in the HDT file.

I'm still not sure whether this is a problem with the dictionary not including that string even though it should, or the `locateInBlock` just failing to find it even if it's there.

**Comment by osma** [comment]
Dumping the contents of the `DictionarySection` for objects indicates that the string `"Seitsemän veljestä"` **is** there. So the lookup fails for some other reason.

**Comment by osma** [comment]
Digging further, I think the problem is the `ReplazableString` class that is used for temporarily holding strings from the dictionary (in the `tempString` variable in `PFCDictionarySection.locateInBlock`). It claims to implement `CharSequence` but internally it uses a set of byte array buffers holding UTF-8 encoded characters. The `CharSequence` method such as `charAt` returns bytes (cast to char) from the UTF-8 representation, which don't match the actual non-ASCII characters in the string. So in the `ByteStringUtils.longestCommonPrefix` method you get a char-by-char comparison between `"SeitsemÃ¤n veljestÃ¤"` (the UTF-8 representation stored internally in the `ReplazableString` buffers) and `"Seitsemän veljestä"` (the looked up string), which obviously won't match.

I think I now know how to fix this - I will make a PR soon. However, performance of lookups may suffer since the internal UTF-8 representation will have to be properly converted to chars/Strings, which is slower than a buffer lookup.

**Comment by osma** [comment]
Actually it's not that simple...the comparison is not done between `String` and `ReplazableString`, but between `CompactString` and `ReplazableString`. They both seem to use UTF-8 encoded bytes internally. Both implement the `charAt` and `length` methods in a way that I think is suspicious (return UTF-8 encoded bytes, or their counts, claiming to be characters), but the comparison should still work. Apparently the internal encoding is somehow different...

**Comment by osma** [comment]
Got it. The problem is an invalid cast from byte to char, where Java considers a byte to be a signed value.
