### ISSUE TITLE
Add support for more RDF formats in Fuseki

### ISSUE THREAD

**Issue by flamingofugang** [rdfhdt/hdt-java#4]
The output format of this Fuseki server is limited, the following do not work:
output=json-ld
output=json-rdf
output=nt
output=ttl

If we serve it as a REST interface service with content negotiation, we need another dependent library to change format...which is not convenient.

Any comment?

**Comment by mielvds** [comment]
@flamingofugang this issue is quite old and the fuseki version should be up-to-date now. Does the problem still occur?
