### ISSUE TITLE
Fuseki default union graph

### ISSUE THREAD

**Issue by sharpaper** [rdfhdt/hdt-java#56]
I think I've been able to setup a Fuseki endpoint with HDT files. I'm wondering, though, if it's possible to setup a "union graph"? According to HDT documentation, I can choose a default graph like this `ja:defaultGraph <#graph-name> ;`, but there is no mention of any "union" graph as the union of all HDT files. Any idea? Or do I have to create an additional HDT file containing the same content of all other HDT files, and use this as `ja:defaultGraph`?

**Comment by larsgsvensson** [comment]
Isn't this a duplicate of #9 ?

**Comment by sharpaper** [comment]
Looks like it is.
