### ISSUE TITLE
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by sharpaper** [rdfhdt/hdt-java#58]
```
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.lang.AbstractStringBuilder.<init>(AbstractStringBuilder.java:68)
	at java.lang.StringBuilder.<init>(StringBuilder.java:89)
	at org.rdfhdt.hdt.hdt.impl.TempHDTImporterOnePass$TripleAppender.processTriple(TempHDTImporterOnePass.java:75)
	at org.rdfhdt.hdt.rdf.parsers.RDFParserSimple.doParse(RDFParserSimple.java:80)
	at org.rdfhdt.hdt.hdt.impl.TempHDTImporterOnePass.loadFromRDF(TempHDTImporterOnePass.java:100)
	at org.rdfhdt.hdt.hdt.HDTManagerImpl.doGenerateHDT(HDTManagerImpl.java:103)
	at org.rdfhdt.hdt.hdt.HDTManager.generateHDT(HDTManager.java:129)
	at org.rdfhdt.hdt.tools.RDF2HDT.execute(RDF2HDT.java:110)
	at org.rdfhdt.hdt.tools.RDF2HDT.main(RDF2HDT.java:175)
```

I get this error when trying to convert a 1GB `.nt` graph to HDT using `rdf2hdt.sh`. My computer has 8GB of RAM. This is also not the largest graph that I need to convert.

How can I convert large graphs to HDT?? For example, how do you convert Wikidata which is ~200GB?

**Comment by mielvds** [comment]
Make sure your configuration uses the "Big" dictionary (https://github.com/rdfhdt/hdt-java/blob/master/hdt-java-core/src/main/java/org/rdfhdt/hdt/dictionary/impl/FourSectionDictionaryBig.java) , should be enabled by default though. (https://github.com/rdfhdt/hdt-java/blob/master/hdt-java-core/hdt.cfg)

I would recommend using the CPP version though, it's more efficient, faster and more stable.

**Comment by sharpaper** [comment]
> I would recommend using the CPP version though, it's more efficient, faster and more stable.

[I got the impression that the CPP version was outdated](https://github.com/rdfhdt/hdt-cpp/issues/111#issuecomment-337484575)? You said "You probably need to generate the HDT file with java too; both libraries might no longer be compatible."

Plus, looks like the CPP version [doesn't compile](https://github.com/rdfhdt/hdt-cpp/issues/110)?

**Comment by mielvds** [comment]
The CPP version definitely has more development going on at the moment, that's why it probably diverted from the java version. I haven't checked, so the HDT's could still be compatible. It does compile for most people AFAIK.

Back to your issue, I honestly don't know. I wasn't involved in the development. But I can imagine that large datasets are a problem for the current implementation, that's why https://github.com/rdfhdt/hdt-mr came about. I could also be an issue with your Garbage Collection configuration.

**Comment by sharpaper** [comment]
> I haven't checked, so the HDT's could still be compatible

regardless if a `.hdt` was created with C++ or Java, shouldn't it be the exact same format?

**Comment by mielvds** [comment]
in theory yes, in practice not that easy without dedicated development teams :/

**Comment by sharpaper** [comment]
Sorry I didn't want to imply that you are not doing enough, I just thought that HDT was more or less a well defined standard and for this reason shouldn't change.

**Comment by mielvds** [comment]
No worries, you didn't imply anything. I just wanted to explain we want the same thing :)

**Comment by kaefer3000** [comment]
You can crank up the heap space (default: 1GB), eg. to 20GB, by prepending your command line using `JAVA_OPTIONS=-Xmx20g`.
