### ISSUE TITLE
Performace: more ram or better disk?

### ISSUE THREAD

**Issue by v4ss4llo** [rdfhdt/hdt-java#63]
Sorry I understand this is not an issue, but I don't see any HDT mailing list or forum where I can ask this. Basically I'm using HDT with Fuseki, and I'd like to understand how are HDT files mapped into memory. When I start Fuseki, what about a HDT file is loaded into RAM? Only the index? And once I start submitting queries, are HDT triples loaded into RAM or read from the hard disk? What happens if the HDT file can't be loaded completely in RAM? Will it swap or will it keep moving new data from disk to ram? Finally, to improve HDT query performance would I be better buying more RAM or a faster disk (SSD) - or something else?

Thank you.

**Comment by MarioAriasGa** [comment]
There are two methods for loading HDTs; load (Creates Java arrays and copies the raw HDT),  and map (Uses mmap from the OS underneath). Bitmaps are critical so they are always kept in memory, the rest of the data structures are just mapped and the operating system will load and keep in memory blocks (typically 4k bytes) using OS-specific policies. The more you use the HDT, the more memory you have, and the less other processess need the memory, the more data will be in RAM and faster will queries be.

If you can choose, the fastest would be having more RAM, falling back to SSD for huge datasets.
