### ISSUE TITLE
wrong asNtriples results

### ISSUE THREAD

**Issue by Vehnem** [rdfhdt/hdt-java#68]
https://github.com/rdfhdt/hdt-java/blob/2b7f1838c06ac872f4e7af4fa0da53678d2835e6/hdt-java-core/src/main/java/org/rdfhdt/hdt/util/string/UnicodeEscape.java#L86

Should be:
'last = i - 1;'

**Comment by MarioAriasGa** [comment]
Thank you for your patch, I have applied it now.
