### ISSUE TITLE
Querying HDT for big datasets

### ISSUE THREAD

**Issue by D063520** [rdfhdt/hdt-java#69]
I was trying query the LOD-a-lot dataset. The dataset is so big that int's are not sufficing as an index for the datastructures used in HDT. So probably the FourSectionDictionaryBig is used. The problem is that while the HDT file can be loaded, it cannot be queried since the 
idToString(int id, TripleComponentRole role)
method uses an int for the id. A long should be possible since the file cannot be queried otherwise.

**Comment by wouterbeek** [comment]
@D063520 Can you try to open the LOD-a-lot file in branch https://github.com/rdfhdt/hdt-java/tree/long-dict-id?  IIUC then this should work.

**Comment by D063520** [comment]
Thank you! This was exactly what I was searching for!
