### ISSUE TITLE
PREFIX http: kills results

### ISSUE THREAD

**Issue by kaefer3000** [rdfhdt/hdt-java#71]
Hi,

I have a set up with Fuseki on top of HDT, data with HTTP URIs (surprise, surprise) in my data set, and when I query using:
```SPARQL
SELECT * WHERE {?s ?p ?o} LIMIT 5
```
I get results. However, when I add the prefix definition for HTTP like
```SPARQL
PREFIX http: <http://www.w3.org/2011/http#>
SELECT * WHERE {?s ?p ?o} LIMIT 5
```
I don't get results any more. When I change the prefix to something else like
```SPARQL
PREFIX htt: <http://www.w3.org/2011/http#>
SELECT * WHERE {?s ?p ?o} LIMIT 5
```
I have results again.

When I fire a query that does not have HTTP URIs in the results (eg. only blank nodes), then `PREFIX http: <...>` does not disturb: I get results with, without, and with the amended prefix.

Cheers!

**Comment by MarioAriasGa** [comment]
Hi Kaefer3000, I have tried with the latest version from master (With latest Jena) and it is not happening. The HDT library doesn't do anything with prefixes so I guess it could be something related to Jena.
