### ISSUE TITLE
Update release on Central Repo of Maven

### ISSUE THREAD

**Issue by pheyvaer** [rdfhdt/hdt-java#78]
Hi,

Would it be possible to update the release on the [Central Repo of Maven](https://search.maven.org/search?q=a:hdt-java-core)? Thanks in advance.

KR
Pieter

**Comment by mielvds** [comment]
See #32 , no resolution. I guess the `eu.wdaqua`is also a volunteer who resolved the issue on his/her own. 

2.1 does not exist yet, however, I'll check whether it can be released and clear up the pom.xml

**Comment by jmkeil** [comment]
As it is not only a pom.xml problem, I opened #83 for the license issue.

**Comment by jmkeil** [comment]
It looks like the eu.wdaqua 2.1 release is based on 19eb9f87ce547290044f436201f3f053f6527cbb.

**Comment by awoods** [comment]
@mielvds : You probably already have full understanding of the process, but in case not:
- In order to publish to Maven Central via Sonatype, you need permissions added by the Sonatype team to their repository.
- Permissions are granted by making a comment on the following ticket asking for your user account to be added :
https://issues.sonatype.org/browse/OSSRH-7790
- Since @MarioAriasGa created the above ticket, and appears to no longer be active, I suspect a comment in the above ticket referencing these GitHub issues will provide sufficient credibility to the request.

As a side note, I would be happy to help with publishing to Maven Central through this process if you run into any issues.

**Comment by awoods** [comment]
@mielvds : If you are interested in commenting on https://issues.sonatype.org/browse/OSSRH-7790 that I (Sonatype user-id: 'awoods') should have right-access to the `org.rdfhdt` group-id, I would be happy to make the Maven Central release happen.

**Comment by mielvds** [comment]
@awoods has this been done or what further action is needed?

**Comment by awoods** [comment]
@mielvds : Based on your request in https://issues.sonatype.org/browse/OSSRH-7790, we have been given permission to publish to Sonatype (and as a flow-through, to Maven Central) artifacts under the `org.rdfhdt` group-id.

Now we have to perform the publication commands. I am happy to help with this... may be easiest to get on a Zoom call.
We will want to use the "Maven Release Plugin": https://maven.apache.org/maven-release/maven-release-plugin/

.. with commands along the lines of:
```
mvn release:prepare -DreleaseVersion=$CURR -DdevelopmentVersion=$NEXT -DautoVersionSubmodules=true -DpushChanges=false
```
and...
```
mvn release:perform -DperformRelease -Dgoals=deploy
```

There will almost certainly be small changes required in the pom.xml(s) in the process.

Let me know if you would like to get on Zoom or Slack. I can be found on:
https://fedora-project.slack.com/
- Self-register at: http://slack.fcrepo.org/

**Comment by jakubklimek** [comment]
Hello, is there any progress on this? There is still only the 2014 1.1 version, and a 2018 version by `eu.wdaqua`

**Comment by awoods** [comment]
Not that I know of. I would be delighted to move a release forward if I could get commit privileges on this repository.

**Comment by mielvds** [comment]
Ok, let's pick this back up. Can't give you priveleges, don't have the permissions. @awoods please drop me an email to schedule a zoomcall to make this happen.

**Comment by mielvds** [comment]
I think it worked! https://search.maven.org/search?q=g:org.rdfhdt. Thanks @awoods for helping me out with the deploy :)

One final thing before I close: can I simply merge https://github.com/rdfhdt/hdt-java/tree/2.1.2-RC with the maven-release-plugin commits in master?

**Comment by awoods** [comment]
That is great, @mielvds . 
Yes, I would suggest merging https://github.com/rdfhdt/hdt-java/commits/2.1.2-RC into the `master` branch as a final step.
Thanks!
