### ISSUE TITLE
Fuseki is counting predicates

### ISSUE THREAD

**Issue by bjonnh** [rdfhdt/hdt-java#79]
[2018-11-06 01:44:02] PredicateIndexArray INFO  Count predicates in 1 hour 16 min 22 sec 104 ms 376 us
for a 2B triples HDT.

Could it use the values from my HDT file? 
 _:triples <http://purl.org/HDT/hdt#triplesnumTriples> "2419923078" 

it takes a few ms to get that from the header.

**Comment by ate47** [comment]
This log message seems to be from the [PredicateIndexArray.generate(ProgressListener):129](https://github.com/rdfhdt/hdt-java/blob/master/hdt-java-core/src/main/java/org/rdfhdt/hdt/triples/impl/PredicateIndexArray.java#L132) method, which is not counting the triples, but loading the sequence of the PredicateIndex, isn't this time normal when we consider the size of the HDT?

**Comment by D063520** [comment]
This occurs at index creation time. Index creation is time and resource consuming. It does not suffice to have an HDT file to query it, you also need the index. If it is not available it will be computed. This is what happening there and explains the long time .....
