### ISSUE TITLE
Clarify the Licenses

### ISSUE THREAD

**Issue by jmkeil** [rdfhdt/hdt-java#83]
Please clarify the licenses. Currently, the LICENSE files, the pom.xml files and some of the source file headers give contradicting statements about that. Fore example:
* hdt-java-core/src/main/java/org/rdfhdt/hdt/hdt/TempHDTImporter.java says *LGPL 2.1+*
* hdt-java-core/LICENSE says *LGPL 3.0*
* hdt-java-core/pom.xml says *LGPL*

**Comment by mielvds** [comment]
core license is now fixed to 3.0
