### ISSUE TITLE
Difference between TempHDTImporterOnePass and TempHDTImporterTwoPass

### ISSUE THREAD

**Issue by jmkeil** [rdfhdt/hdt-java#85]
As far as I understand, there is no difference between the HDT produced by `TempHDTImporterOnePass `and `TempHDTImporterTwoPass`, but in the processing order. What is the advantage of `TempHDTImporterTwoPass`, especially as it doubles the IO / Traffic by consuming the (remote) source file twice?

**Comment by mielvds** [comment]
The advantage is that it's less memory intensive.
