### ISSUE TITLE
Provide HDTManager::generateHDT consuming an InputStream

### ISSUE THREAD

**Issue by jmkeil** [rdfhdt/hdt-java#86]
It would be very helpful to have a method `HDTManager::generateHDT(InputStream, String, RDFNotation, HDTOptions, ProgressListener)`, which consumes a `InputStream` instead of a file path.

In case of `TempHDTImporterOnePass` it is quiet straightforward to do that. In case of `TempHDTImporterTwoPass` the things are more complicated, as the `InputStream` would be needed to consume twice.

**Comment by mielvds** [comment]
@jmkeil good suggestion! it would be too complicated with `TempHDTImporterTwoPass` though.   always welcome to submit a PR

**Comment by jmkeil** [comment]
> @jmkeil […] always welcome to submit a PR

As I decided against using HDT in my project, I don't have time to do that. Sorry.

**Comment by ate47** [comment]
It was implemented with #162 at this line:

https://github.com/rdfhdt/hdt-java/blob/912276e93f2ad4f4bf864aaca8802b5be2e22a11/hdt-api/src/main/java/org/rdfhdt/hdt/hdt/HDTManager.java#L483

So we can close this issue :)
